version: '3.8'

services:
  api:
    container_name: api-prod
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '80:80'

  chat:
    container_name: chat-prod
    build:
      context: .
      dockerfile: apps/chat/Dockerfile.prod
    ports:
      - '80:80'

  prisma:
    image: prismagraphql/prisma:1.33
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: mysecret42
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo-db

  mongo-db:
    image: mongo:4.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo: ~
