mutation createUser($name: String!) {
  createUser(name: $name) {
    id
    name
  }
}

query users {
  users {
    id
    name
  }
}

mutation createChannel($name: String!) {
  createChannel(name: $name) {
    id
    name
  }
}
